spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhouruizhong/spring-cloud-config
          search-paths: respo
          username: zhouruizhong
          password: zhouruizhong@809

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/